name: Deploy test dir to gh-page

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: リポジトリをチェックアウト
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: 仮フォルダのセットアップ
              run: |
                  mkdir output
                  cp -r test/* output/

            - name: gh-page ブランチにデプロイ
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./output
                  publish_branch: gh-page
                  force_orphan: true
