name: Generate .d.ts

on:
    workflow_run:
        workflows: ["Release on Version Change"]
        types:
            - completed
    push:
        tags:
            - "v*"

permissions:
    contents: write # リポジトリのコンテンツに書き込み権限を与える

jobs:
    generate-dts:
        runs-on: ubuntu-latest

        steps:
            - name: リポジトリをチェックアウト
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Node.js をセットアップ
              uses: actions/setup-node@v4
              with:
                  node-version: "18"

            - name: TypeScript をインストール
              run: npm install --save-dev typescript

            - name: tsconfig.json を作成
              run: |
                  echo '{
                    "compilerOptions": {
                      "allowJs": true,
                      "declaration": true,
                      "emitDeclarationOnly": true,
                      "outDir": "types"
                    },
                    "include": ["dist/*.js"]
                  }' > tsconfig.json

            - name: .d.ts を生成
              run: npx tsc

            - uses: actions/upload-artifact@v4
              with:
                  if-no-files-found: error
                  path: types/*

            - name: 最新のタグを取得
              id: get_tag
              run: |
                  TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
                  echo "tag=$TAG" >> $GITHUB_OUTPUT

            - name: Upload .d.ts to existing release
              uses: softprops/action-gh-release@v1
              with:
                  files: types/*.d.ts # .d.tsファイルをアップロード
                  tag_name: ${{ steps.get_tag.outputs.tag }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
